run:
    seed: 0
    name: 
    redo: false
    wandb: true

sample:
    importance_sample: false
    n_cond: 75
    clone_size: 7
    n_particles: 4
    n_resample: 4
    max_steps: 3
    total_mcmc_steps: 110

likelihoods:
    label_noise_sigma: 0.25
    max_gen_batch_size: 200
    n_cond: ${sample.n_cond}

oracle:
    n_labelled_mut: 2
    start_ind: 0
    oracle_name: clone
